### ISSUE TITLE
Automatic compatibility with Twitter Bootstrap

### ISSUE THREAD

**Issue by vojtech-dobes** [vojtech-dobes/nette-forms-gpspicker#1]
``` css
[data-nette-gpspicker] img {
    max-width: none;
}
```
- [ ] popovers
- [x] issue with max-width
